Import of MIKER/Net-Interface-1.004 from CPAN.
gitpan-cpan-distribution: Net-Interface
gitpan-cpan-version:      1.004
gitpan-cpan-path:         MIKER/Net-Interface-1.004.tar.gz
gitpan-cpan-author:       MIKER
gitpan-cpan-maturity:     released

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1693,6 +1693,12 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 # but does not  check if it is usable
 
 
+# AX_IN_STDLIB(lowercase_funcname, UPPERCASE_FUNCNAME)
+# ---------------------------------------------------------
+# checks if the function is present in the netinet/in.h file
+# and sets SIZEOF_SOCKFUNC if found
+
+
 ac_config_headers="$ac_config_headers config.h"
 
 
@@ -4476,6 +4482,55 @@ fi
 
 
 
+
+
+
+{ echo "$as_me:$LINENO: checking for MALLOC in stdlib.h" >&5
+echo $ECHO_N "checking for MALLOC in stdlib.h... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+
+#include <stdlib.h>
+int
+main()
+{
+    void * mem = malloc(8192);
+    return 1;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_MALLOC_IN_STDLIB 1
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: not defined" >&5
+echo "${ECHO_T}not defined" >&6; }
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext;
 
 # Checks for header files.
 
